version: "3.8"
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - N8N_HOST=${RAILWAY_PUBLIC_DOMAIN}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://${RAILWAY_PUBLIC_DOMAIN}/
      - GENERIC_TIMEZONE=Europe/London
      - N8N_METRICS=true
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
